name: üî® Build and push Moodle images to Artifactory

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  APP: moodle
  USER: ${{ github.actor }}

on:
  push:
    branches:
      #- dev
      #- test
      #- prod
    paths:
      # - '**.Dockerfile'
      # - '**/config/**'
      # - '**/workflows/build-moodle-jfrog.yml'
  pull_request:
    branches:
      # - dev
      #- test
      #- prod
    paths:
      # - '**.Dockerfile'
      # - '**/config/**'
      # - '**/workflows/build-moodle-jfrog.yml'
jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: üìã Environment Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Env Vars
        run: |
          echo Building ${{ env.APP }}:${{ github.ref_name }}

  # Build Images

  build-images:
    name: 'üî® Build all Moodle images (web, cron, dp, php, moodle)'
    needs: [checkEnv]
    runs-on: ubuntu-latest
    if: ${{ needs.checkEnv.SKIP_BUILDS != 'YES' }} && (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
      # Checkout the PR branch
      - name: üì§ Checkout Target Branch
        uses: actions/checkout@v2

      # Login to Artifactory
      - name: üîë Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Pull/tag base images
      - name: üõ†Ô∏è Pull Web Image
        shell: bash
        run: |
          docker pull ${{env.WEB_IMAGE}}
          docker tag ${{env.WEB_IMAGE}} ${{ secrets.ARTIFACTORY_URL }}/${{env.WEB_IMAGE}}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{env.WEB_IMAGE}}

      - name: üõ†Ô∏è Pull Cron Image
        run: |
          docker pull ${{env.CRON_IMAGE}}
          docker tag ${{env.CRON_IMAGE}} ${{ secrets.ARTIFACTORY_URL }}/${{env.CRON_IMAGE}}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{env.CRON_IMAGE}}

      - name: üõ†Ô∏è Pull DB Image
        run: |
          docker pull ${{env.DB_IMAGE}}
          docker tag ${{env.DB_IMAGE}} ${{ secrets.ARTIFACTORY_URL }}/${{env.DB_IMAGE}}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{env.DB_IMAGE}}

      - name: üõ†Ô∏è Pull PHP Image
        run: |
          docker pull ${{env.PHP_IMAGE}}
          docker tag ${{env.PHP_IMAGE}} ${{ secrets.ARTIFACTORY_URL }}/${{env.PHP_IMAGE}}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{env.PHP_IMAGE}}

      # Build / push images to Artifactory
      - name: üõ†Ô∏è Build Moodle Image
        run: |
          docker buildx build --tag ${{ secrets.ARTIFACTORY_URL }}/${{ env.MOODLE_DEPLOYMENT_NAME }}:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} --output=type=image,push=true --push -f Moodle.Dockerfile .

      - name: üõ†Ô∏è Build PHP Image
        run: |
          docker buildx build --tag ${{ secrets.ARTIFACTORY_URL }}/${{ PHP_DEPLOYMENT_NAME }}:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} --output=type=image,push=true --push -f PHP.Dockerfile .

      - name: üõ†Ô∏è Build CRON Image
        run: |
          docker buildx build --tag ${{ secrets.ARTIFACTORY_URL }}/${{ CRON_DEPLOYMENT_NAME }}:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} --output=type=image,push=true --push -f CRON.Dockerfile .
