# Deploy On Openshift
# Builds and Deploys merged PR's to persistent pods/services/routes/etc in the OpenShift environment.
name: ðŸš€ Deploy on Openshift

env:
  APP: moodle
  USER: ${{ github.actor }}

on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      BASE_IMAGE_TAG:
        required: true
        type: string
      DB_DEPLOYMENT_NAME:
        required: true
        type: string
      DB_IMAGE:
        required: true
        type: string
      BRANCH:
        required: true
        type: string
      APP_HOST_URL:
        required: true
        type: string
      BUILD_NAMESPACE:
        required: true
        type: string
      DEPLOY_NAMESPACE:
        required: true
        type: string
      WEB_DEPLOYMENT_NAME:
        required: true
        type: string
      WEB_IMAGE:
        required: true
        type: string
      PHP_IMAGE:
        required: true
        type: string
      PHP_DEPLOYMENT_NAME:
        required: true
        type: string
      CRON_IMAGE:
        required: true
        type: string
      CRON_DEPLOYMENT_NAME:
        required: true
        type: string
      REDIS_DEPLOYMENT_NAME:
        required: true
        type: string
      REDIS_IMAGE:
        required: true
        type: string
    secrets:
      AUTH_TOKEN_DEV:
        required: true
      AUTH_TOKEN_TEST:
        required: true
      AUTH_TOKEN_PROD:
        required: true
    outputs:
      # This is the name of the output set by the workflow_dispatch action.
      # The value is the ID of the workflow run that was triggered.
      deploy1:
        description: "Deployment log"
        value: ${{ jobs.deploy.outputs.output1 }}
      deploy2:
        description: "Deployment log"
        value: ${{ jobs.deploy.outputs.output2 }}
  # push:
  #   paths:
  #     - './openshift/*'
  #     - '**.Dockerfile'
  #     - '**.yml'
  #     - '**.conf'
  #     - '**.ini'
  #     - '**.php'
permissions:
  contents: read
  id-token: write

jobs:
  # Deploy to Openshift
  deploy:
    name: ðŸš€ Deploy to OpenShift (${{ github.ref_name }})
    runs-on: ubuntu-latest
    if: |
      always()
      && (
        github.ref_name == 'dev' || github.ref_name  == 'test' || github.ref_name  == 'prod'
      ) || (
        contains(github.event.workflow_run.conclusion, 'success')
        && !contains(github.event.workflow_run.conclusion, 'failure')
      )
    outputs:
      output1: ${{ steps.deploy-to-os.outputs.deploy1 }}
      output2: ${{ steps.deploy-to-os.outputs.deploy2 }}
    steps:
      - name: ðŸ“¤ Checkout Target Branch
        uses: actions/checkout@v2

      # Get Environment Variables from file
      - name: ðŸ“‹ Setup Environment from File
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: example.env
          export-variables: true
          log-variables: true
          keys-case: upper

      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: ðŸ”‘ Log in to OpenShift ( DEV )
        if: github.ref_name == 'dev'
        run: |
          oc login --token=${{ secrets.AUTH_TOKEN_DEV }} --server=https://api.silver.devops.gov.bc.ca:6443

      - name: ðŸ”‘ Log in to OpenShift ( TEST )
        if: github.ref_name == 'test'
        run: |
          oc login --token=${{ secrets.AUTH_TOKEN_TEST }} --server=https://api.silver.devops.gov.bc.ca:6443

      - name: ðŸ”‘ Log in to OpenShift ( PROD )
        if: github.ref_name == 'prod'
        run: |
          oc login --token=${{ secrets.AUTH_TOKEN_PROD }} --server=https://api.silver.devops.gov.bc.ca:6443

      - name: ðŸ” Check for ${{ inputs.REDIS_DEPLOYMENT_NAME }}
        id: check-redis
        run: |
          if [[ `oc describe sts ${{ inputs.REDIS_DEPLOYMENT_NAME  }} 2>&1` =~ "NotFound" ]]; then
          echo "${{ inputs.REDIS_DEPLOYMENT_NAME  }} NOT FOUND: Beginning deployment..."
          echo "installed=false" >> $GITHUB_OUTPUT
          else
            echo "${{ inputs.REDIS_DEPLOYMENT_NAME  }} FOUND: Moving on..."
            echo "installed=true" >> $GITHUB_OUTPUT
          fi

      # - name: Uninstall ${{ inputs.REDIS_DEPLOYMENT_NAME }}
      #   run: helm uninstall ${{ inputs.REDIS_DEPLOYMENT_NAME }} -n ${{ inputs.DEPLOY_NAMESPACE }} --wait

      - name: ðŸš€ Deploy Redis | ${{ inputs.REDIS_DEPLOYMENT_NAME }} | ${{ inputs.REDIS_IMAGE }}
        if: ${{ steps.check-redis.outputs.installed == 'false' }}
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install ${{ inputs.REDIS_DEPLOYMENT_NAME }} ${{ inputs.REDIS_IMAGE }} --set securityContext.runAsUser=null --set securityContext.fsGroup=null -f ./config/redis/values.yml

      - name: ðŸ” Check for DB (MariaDB Galera) Statefulset (${{ inputs.DB_DEPLOYMENT_NAME }})
        id: check-db
        run: |
          if [[ `oc describe sts ${{ inputs.DB_DEPLOYMENT_NAME  }} 2>&1` =~ "NotFound" ]]; then
          echo "${{ inputs.DB_DEPLOYMENT_NAME  }} NOT FOUND: Beginning deployment..."
          echo "installed=false" >> $GITHUB_OUTPUT
          else
            echo "${{ inputs.DB_DEPLOYMENT_NAME  }} FOUND: Moving on..."
            echo "installed=true" >> $GITHUB_OUTPUT
          fi

      # For a graceful termination, set the replica count of the Pods in the mariadb-galera StatefulSet to 0:
      # oc scale sts ${{ inputs.DB_DEPLOYMENT_NAME  }} --replicas=0
      # To uninstall/delete the my-release release:
      # helm delete --purge ${{ inputs.DB_DEPLOYMENT_NAME  }}
      - name: ðŸš€ Deploy DB (MariaDB Galera) [is it installed already? ${{ steps.check-db.outputs.installed }}]
        if: ${{ steps.check-db.outputs.installed == 'false' }}
        run: |
          oc create -f ./config/mariadb/config.yaml -n ${{ inputs.DEPLOY_NAMESPACE }}

      # - name: 'ðŸš€ Deploy DB (MariaDB Galera) via Helm bot'
      #   uses: 'deliverybot/helm@v1'
      #   with:
      #     release: '${{ inputs.DB_DEPLOYMENT_NAME }}'
      #     namespace: '${{ github.ref_name }}'
      #     chart: '${{ inputs.DB_IMAGE }}'
      #     token: '${{ github.token }}'
      #     values: |
      #       name: ${{ inputs.DB_DEPLOYMENT_NAME }}
      #     value-files: >-
      #       [
      #         "./config/mariadb/config.yaml"
      #       ]

      - name: ðŸš€ Deploy OpenShift Template ( ${{ inputs.DEPLOY_NAMESPACE }} ) ${{ inputs.WEB_DEPLOYMENT_NAME }}, ${{ inputs.PHP_DEPLOYMENT_NAME }}, ${{ inputs.CRON_DEPLOYMENT_NAME }} - with routes, secrets, configmaps
        id: deploy-to-os
        # if: success() || failure()
        if: success()
        run: sh ./openshift/scripts/deploy-template.sh
        env:
          APP: ${{ inputs.APP }}
          BRANCH: ${{ inputs.BRANCH }}
          APP_HOST_URL: ${{ inputs.APP_HOST_URL }}
          BUILD_NAMESPACE: ${{ inputs.BUILD_NAMESPACE }}
          DEPLOY_NAMESPACE: ${{ inputs.DEPLOY_NAMESPACE }}
          BASE_IMAGE_TAG: ${{ inputs.BASE_IMAGE_TAG }}
          WEB_DEPLOYMENT_NAME: ${{ inputs.WEB_DEPLOYMENT_NAME }}
          WEB_IMAGE: ${{ inputs.WEB_IMAGE }}
          PHP_DEPLOYMENT_NAME: ${{ inputs.PHP_DEPLOYMENT_NAME }}
          PHP_IMAGE: ${{ inputs.PHP_IMAGE }}
          CRON_DEPLOYMENT_NAME: ${{ inputs.CRON_DEPLOYMENT_NAME }}
          CRON_IMAGE: ${{ inputs.CRON_IMAGE }}
          REDIS_DEPLOYMENT_NAME: ${{ inputs.REDIS_DEPLOYMENT_NAME }}
